#!/usr/bin/env python

import findrox; findrox.version(2, 0, 0)
import rox, os, sys, gtk

try:
	__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

	from optparse import OptionParser

	parser = OptionParser()
	parser.add_option("--options",
		action="store_true", dest="options", default=False,
		help="display options dialog")

	parser.add_option("--accounts",
		action="store_true", dest="accounts", default=False,
		help="edit accounts list")
		
	(options, args) = parser.parse_args()

	if options.options:
		import postal
		rox.edit_options()
		rox.mainloop()
	elif options.accounts:
		import postal
		box = postal.Postal(-1)  #don't fully initialize the applet
		box.load_accounts()
		box.edit_accounts()
		rox.mainloop()
	else:
		rox.info(_("This is a panel applet.  Drag it to your panel to run it."))

except:
	rox.report_exception()
