#!/bin/sh

echo Extracting messages from source files...
echo

(
  cd ..
  xgettext -o - -L Python *.py AppRun AppletRun |
  sed "s/charset=CHARSET/charset=UTF-8/" > pot.tmp
  echo >> pot.tmp
  python Messages/opts2po.py Options.xml >> pot.tmp
  msguniq -o Messages/messages.pot pot.tmp
  rm pot.tmp
)

echo
echo Updating all .po files...
echo

find . -name \*.po -exec msgmerge -U \{\} messages.pot \;
